src/Entity/Answers.php
<?php

namespace App\Entity;

use App\Repository\AnswersRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnswersRepository::class)]
class Answers
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Question::class, inversedBy: 'answers')]
    private $id_question;

    #[ORM\Column(type: 'text')]
    private $Label;

    #[ORM\Column(type: 'boolean')]
    private $isTrue;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdQuestion(): ?question
    {
        return $this->id_question;
    }

    public function setIdQuestion(?question $id_question): self
    {
        $this->id_question = $id_question;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->Label;
    }

    public function setLabel(string $Label): self
    {
        $this->Label = $Label;

        return $this;
    }

    public function isIsTrue(): ?bool
    {
        return $this->isTrue;
    }

    public function setIsTrue(bool $isTrue): self
    {
        $this->isTrue = $isTrue;

        return $this;
    }
}

src/Entity/QCM.php
<?php

namespace App\Entity;

use App\Repository\QCMRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QCMRepository::class)]
class QCM
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Title;

    #[ORM\Column(type: 'text', nullable: true)]
    private $Description;

    #[ORM\Column(type: 'time')]
    private $Time;

    #[ORM\OneToMany(mappedBy: 'id_QCM', targetEntity: Question::class)]
    
    private $questions;



    public function __construct()
    {
        $this->questions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->Time;
    }

    public function setTime(\DateTimeInterface $Time): self
    {
        $this->Time = $Time;

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setIdQCM($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getIdQCM() === $this) {
                $question->setIdQCM(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->id; 
    }
}

src/Form/QCMType.php
<?php

namespace App\Form;

use App\Entity\QCM;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QCMType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Title')
            ->add('Description')
            ->add('Time')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Qcm::class,
        ]);
    }
}

src/Controller/QCMController.php
<?php

namespace App\Controller;

use App\Entity\QCM;
use App\Entity\StudentAnswer;
use App\Form\QCMType;
use App\Form\StudentAnswerType;
use App\Repository\QCMRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Question;
use App\Entity\Answers;
use App\Repository\QuestionRepository;
use App\Form\AnswersType; // Importing AnswerType
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


#[Route('/qcm')]
class QCMController extends AbstractController
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/', name: 'app_q_c_m_index', methods: ['GET'])]
    public function index(QCMRepository $qCMRepository): Response
    {
        return $this->render('qcm/index.html.twig', [
            'q_c_ms' => $qCMRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_q_c_m_new', methods: ['GET', 'POST'])]
    public function new(Request $request, QCMRepository $qCMRepository): Response
    {
        $qCM = new QCM();
        $form = $this->createForm(QCMType::class, $qCM);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $qCMRepository->add($qCM, true);

            return $this->redirectToRoute('app_q_c_m_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('qcm/new.html.twig', [
            'q_c_m' => $qCM,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_q_c_m_show', methods: ['GET'])]
    public function show(QCM $qCM): Response
    {
        return $this->render('qcm/show.html.twig', [
            'q_c_m' => $qCM,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_q_c_m_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, QCM $qCM, QCMRepository $qCMRepository): Response
    {
        $form = $this->createForm(QCMType::class, $qCM);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $qCMRepository->add($qCM, true);

            return $this->redirectToRoute('app_q_c_m_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('qcm/edit.html.twig', [
            'q_c_m' => $qCM,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_q_c_m_delete', methods: ['POST'])]
    public function delete(Request $request, QCM $qCM, QCMRepository $qCMRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$qCM->getId(), $request->request->get('_token'))) {
            $qCMRepository->remove($qCM, true);
        }

        return $this->redirectToRoute('app_q_c_m_index', [], Response::HTTP_SEE_OTHER);
    }


    #[Route("/qcm/{id}/answer", name: "app_qcm_answer", methods: ['POST'])]
    public function answer(Request $request, Qcm $qcm)
    {
        $em = $this->entityManager;
    
        // Récupérer toutes les questions du QCM
        $questions = $qcm->getQuestions();
    
        // Traiter la soumission de chaque formulaire de question
        foreach ($questions as $question) {
            $form = $this->createFormBuilder()
                ->add('answer', ChoiceType::class, [
                    'choices' => $question->getAnswers(),
                    'expanded' => true,
                    'multiple' => false,
                    'choice_label' => 'label',
                ])
                ->getForm();
    
            $form->handleRequest($request);
    
            if ($form->isSubmitted() && $form->isValid()) {
                $answer = $form->get('answer')->getData();
    
                // Créer une nouvelle instance de StudentAnswer
                $studentAnswer = new StudentAnswer();
                $studentAnswer->setQcmId($qcm);
                $studentAnswer->setQuestionid($question);
                $studentAnswer->setUserid($this->getUser());
    
                // Enregistrer l'instance de StudentAnswer dans la base de données
                $em->persist($studentAnswer);
                $em->flush();
            }
        }
    
        // Rediriger l'utilisateur vers la page de résultats
        return $this->redirectToRoute('app_qcm_results', ['id' => $qcm->getId()]);
    }
    
    #[Route("/qcm/{id}/start", name:"app_qcm_start")]
    public function start(Request $request, Qcm $qcm): Response
    {

        dump($request->query->all());
        $questions = $qcm->getQuestions();
        $totalQuestions = count($questions);
        $questionIndex = $request->query->getInt('question', 0);
    
        if ($questionIndex >= $totalQuestions) {
            return $this->redirectToRoute('app_qcm_results', ['id' => $qcm->getId()]);
        }
    
        $question = $questions[$questionIndex];
        $studentAnswer = new StudentAnswer();
        $studentAnswer->setUserId($this->getUser());
        $studentAnswer->setQcmId($qcm);
        $studentAnswer->setQuestionId($question);
    
        $form = $this->createForm(StudentAnswerType::class, $studentAnswer);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            // Traitez la soumission du formulaire et enregistrez la réponse
            $this->entityManager->persist($studentAnswer);
            $this->entityManager->flush();
    
            // Redirigez vers la question suivante ou les résultats
            if ($questionIndex < $totalQuestions - 1) {
                return $this->redirectToRoute('app_qcm_start', ['id' => $qcm->getId(), 'question' => $questionIndex + 1]);
            } else {

                return $this->redirectToRoute('app_qcm_results', ['id' => $qcm->getId()]);
            }
        }
    
        return $this->render('qcm/question.html.twig', [
            'qcm' => $qcm,
            'question' => $question,
            'questions' => $questions,
            'form' => $form->createView(),
            'questionIndex' => $questionIndex + 1,
            'totalQuestions' => $totalQuestions,
        ]);
    }
    

    #[Route('/{id}/results', name: 'app_qcm_results', methods: ['GET'])]
    public function results(QCM $qcm): Response
    {
        $studentAnswers = $this->entityManager->getRepository(StudentAnswer::class)->findBy(['Qcm_id' => $qcm]);
    
        // Afficher les réponses des étudiants avec dump()
        dump($studentAnswers);
    
        $score = 0;
        $totalQuestions = count($qcm->getQuestions());
    
        foreach ($studentAnswers as $studentAnswer) {
            if ($studentAnswer->getAnswersId()->isIsTrue()) {
                $score++;
            }
        }
    
        // Afficher le score avec dump()
        dump($score);
    
        return $this->render('qcm/results.html.twig', [
            'qcm' => $qcm,
            'score' => $score,
            'totalQuestions' => $totalQuestions,
            'studentAnswers' => $studentAnswers,
        ]);
    }
    
    public function result(Request $request, QCM $qcm, EntityManagerInterface $entityManager)
    {
        // Récupérer les données soumises par le formulaire
        $submittedData = $request->request->all();
    
        // Créer une instance de StudentAnswer pour chaque réponse soumise
        foreach ($submittedData as $questionId => $answerId) {
            // Récupérer les entités correspondantes à l'ID de la question et de la réponse
            $question = $entityManager->getRepository(Question::class)->find($questionId);
            $answer = $entityManager->getRepository(Answers::class)->find($answerId);
    
            // Créer une nouvelle instance de StudentAnswer et la remplir
            $studentAnswer = new StudentAnswer();
            $studentAnswer->setUserId($this->getUser()); // À adapter selon votre logique d'utilisateur connecté
            $studentAnswer->setQcmId($qcm);
            $studentAnswer->setQuestionId($question);
            $studentAnswer->setAnswersId($answer);
            $studentAnswer->setResult(null); // À adapter selon vos besoins
    
            // Enregistrer l'entité StudentAnswer dans la base de données
            $entityManager->persist($studentAnswer);
        }
    
        // Flush pour enregistrer toutes les instances de StudentAnswer
        $entityManager->flush();
    
        // Calculer le pourcentage après avoir sauvegardé les réponses
        $score = 0;
        $totalQuestions = count($qcm->getQuestions());
    
        // Calcule le score de l'utilisateur
        foreach ($qcm->getQuestions() as $question) {
            $correctAnswerId = null;
            foreach ($question->getAnswers() as $answer) {
                if ($answer->isIsTrue()) {
                    $correctAnswerId = $answer->getId();
                    break;
                }
            }
    
            if (isset($submittedData[$question->getId()]) && $submittedData[$question->getId()] == $correctAnswerId) {
                $score++;
            }
        }
    
        $percentage = ($score / $totalQuestions) * 100;
    
        // Redirection vers une autre page après traitement
        return $this->redirectToRoute('app_qcm_results', ['id' => $qcm->getId(), 'percentage' => $percentage]);
    }    
}    

templates/qcm/_delete_form.html.twig
<form method="post" action="{{ path('app_q_c_m_delete', {'id': q_c_m.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ q_c_m.id) }}">
    <button class="btn">Delete</button>
</form>

templates/qcm/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/qcm/answer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Répondre au QCM{% endblock %}

{% block body %}
    <h1>Répondre au QCM : {{ qcm.title }}</h1>

    {% if qcm.description %}
        <p>{{ qcm.description }}</p>
    {% endif %}

    <form method="POST" action="{{ path('app_qcm_answer', {'id': qcm.id}) }}">
        {{ form_start(form) }}
        {% for question in qcm.questions %}
            <h3>Question {{ loop.index }}: {{ question.label }}</h3>

            {% for answer in question.answers %}
                <div>
                    <input type="radio" id="answer_{{ answer.id }}" name="answersId[{{ loop.index0 }}]" value="{{ answer.id }}" required>
                    <label for="answer_{{ answer.id }}">{{ answer.label }}</label>
                </div>
            {% endfor %}
        {% endfor %}

        <button type="submit">Soumettre les réponses</button>
        {{ form_end(form) }}
    </form>
{% endblock %}

templates/qcm/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit QCM{% endblock %}

{% block body %}
    <h1>Edit QCM</h1>

    {{ include('qcm/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_q_c_m_index') }}">back to list</a>

    {{ include('qcm/_delete_form.html.twig') }}
{% endblock %}

templates/qcm/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-between mb-3">
            <div class="col-auto">
                <h1 class="my-4">Liste des QCM</h1>
            </div>
        {% if is_granted('ROLE_ADMIN') %}
            <div class="col-auto">
                <a href="{{ path('app_q_c_m_new') }}" class="btn btn-success">Add QCM</a>
                <a href="{{ path('app_question_new') }}" class="btn btn-primary">Add Question</a>
                <a href="{{ path('app_answers_new') }}" class="btn btn-info">Add Answer</a> {# Ajout du lien pour ajouter une réponse #}
            </div>
        {% endif %}
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% for q_c_m in q_c_ms %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ q_c_m.title }}</h5>
                            <p class="card-text">
                                {{ q_c_m.description }}<br>
                                {{ q_c_m.Time ? q_c_m.Time|date('H:i') : '' }}<br>
                            </p>
                            <a href="{{ path('app_qcm_start', {'id': q_c_m.id}) }}" class="btn btn-primary">Commencer le QCM</a>
                        </div>
                    </div>
                {% else %}
                    <p>Aucun QCM disponible.</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/qcm/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New QCM{% endblock %}

{% block body %}
    <h1>Create new QCM</h1>

    {{ include('qcm/_form.html.twig') }}

    <a href="{{ path('app_q_c_m_index') }}">back to list</a>
{% endblock %}

templates/qcm/question.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="text-center my-4">{{ qcm.title }}</h1>
                <form method="POST" action="{{ path('app_qcm_answer', {'id': qcm.id}) }}">
                {% for question in questions %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">Question {{ loop.index }}: {{ question.label }}</h5>
                            {% for answer in question.answers %}
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="question_{{ question.id }}" id="answer_{{ answer.id }}" value="{{ answer.id }}">
                                    <label class="form-check-label" for="answer_{{ answer.id }}">
                                        {{ answer.label }}
                                    </label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    <p>Aucune question disponible.</p>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Soumettre les réponses</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/qcm/results.html.twig
{% extends 'base.html.twig' %}

{% block title %}Résultats du QCM{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-4">Résultats du QCM "{{ qcm.title }}"</h1>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Étudiant</th>
                    <th scope="col">Question</th>
                    <th scope="col">Réponse donnée</th>
                    <th scope="col">Est Correcte</th>
                </tr>
            </thead>
            <tbody>
                {% for studentAnswer in studentAnswers %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        <td>{{ studentAnswer.getUserId().getUsername() }}</td>
                        <td>{{ studentAnswer.getQuestionId().getLabel() }}</td>
                        <td>{{ studentAnswer.getAnswersId().getLabel() }}</td>
                        <td>{% if studentAnswer.getAnswersId().isIsTrue() %}Oui{% else %}Non{% endif %}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5">Aucune réponse enregistrée pour ce QCM.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/qcm/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}QCM{% endblock %}

{% block body %}
    <h1>QCM</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ q_c_m.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ q_c_m.Title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ q_c_m.Description }}</td>
            </tr>
            <tr>
                <th>Time</th>
                <td>{{ q_c_m.Time ? q_c_m.Time|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_q_c_m_index') }}">back to list</a>

    <a href="{{ path('app_q_c_m_edit', {'id': q_c_m.id}) }}">edit</a>

    {{ include('qcm/_delete_form.html.twig') }}
{% endblock %}